#!/bin/bash

echo "🚨 ============================================"
echo "🚨 SERVIDOR PRECISA SER REINICIADO!"
echo "🚨 ============================================"
echo ""
echo "❌ PROBLEMA:"
echo "   O servidor está rodando o CÓDIGO ANTIGO"
echo "   Que olha o campo 'listed' (desatualizado)"
echo ""
echo "✅ SOLUÇÃO:"
echo "   Reiniciar para carregar o código NOVO"
echo "   Que faz JOIN com tabela 'offers'"
echo ""
echo "🎯 AÇÃO:"
echo "   1. Vá ao terminal onde 'npm start' está rodando"
echo "   2. Pressione Ctrl + C"
echo "   3. Aguarde 2 segundos"
echo "   4. Digite: npm start"
echo "   5. Aguarde aparecer: 'Server running on port 3000'"
echo ""
echo "📋 VERIFICAÇÃO:"
echo "   Após reiniciar, execute:"
echo "   curl http://localhost:3000/api/ordinals?listed=true"
echo ""
echo "   ✅ DEVE RETORNAR:"
echo "   {\"inscriptions\":[]}"
echo "   (vazio, porque não tem ofertas)"
echo ""
echo "🧹 BANCO LIMPO:"
sqlite3 server/db/ordinals.db "SELECT COUNT(*) as offers FROM offers;"
echo "   Ofertas: ^^ (deve ser 0)"
echo ""
sqlite3 server/db/ordinals.db "SELECT inscription_number, listed FROM inscriptions;"
echo "   Inscription: ^^ (listed deve ser 0)"
echo ""
echo "🚀 AGORA REINICIE O SERVIDOR!"
echo "🚨 ============================================"




